// =====================================================
// MOCK DATA FOR STREET ECOMMERCE
// =====================================================

export const products = [
  {
    id: 1,
    name: "Urban Runner Pro",
    category: "Shoes",
    price: 129.99,
    originalPrice: 179.99,
    rating: 4.8,
    reviews: 234,
    badge: "HOT",
    image: "https://picsum.photos/seed/urbanrunner/800/1000",
    images: [
      "https://picsum.photos/seed/urbanrunner/800/1000",
      "https://picsum.photos/seed/urbanrunner2/800/1000",
      "https://picsum.photos/seed/urbanrunner3/800/1000",
      "https://picsum.photos/seed/urbanrunner4/800/1000",
    ],
    description:
      "The Urban Runner Pro is engineered for the streets. Featuring a premium cushioned sole with breathable mesh upper, this sneaker combines performance and style seamlessly. Perfect for long walks, casual outings, or light athletic activities.",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: ["#1a1a1a", "#ffffff", "#8b5cf6", "#3b82f6"],
    colorNames: ["Black", "White", "Purple", "Blue"],
    inStock: true,
    featured: true,
    trending: true,
  },
  {
    id: 2,
    name: "Street Core Hoodie",
    category: "Hoodies",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.9,
    reviews: 412,
    badge: "NEW",
    image: "https://picsum.photos/seed/streetcore/800/1000",
    images: [
      "https://picsum.photos/seed/streetcore/800/1000",
      "https://picsum.photos/seed/streetcore2/800/1000",
      "https://picsum.photos/seed/streetcore3/800/1000",
      "https://picsum.photos/seed/streetcore4/800/1000",
    ],
    description:
      "The Street Core Hoodie is your ultimate urban companion. Crafted from heavyweight 400gsm fleece cotton blend, it offers premium warmth and durability. Features a spacious kangaroo pocket, adjustable drawstring hood, and ribbed cuffs.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#1a1a1a", "#2d2d2d", "#8b5cf6", "#374151"],
    colorNames: ["Jet Black", "Charcoal", "Purple Haze", "Storm Gray"],
    inStock: true,
    featured: true,
    trending: true,
  },
  {
    id: 3,
    name: "Classic Logo Tee",
    category: "T-Shirts",
    price: 44.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 678,
    badge: "SALE",
    image: "https://picsum.photos/seed/classiclogo/800/1000",
    images: [
      "https://picsum.photos/seed/classiclogo/800/1000",
      "https://picsum.photos/seed/classiclogo2/800/1000",
      "https://picsum.photos/seed/classiclogo3/800/1000",
      "https://picsum.photos/seed/classiclogo4/800/1000",
    ],
    description:
      "The Classic Logo Tee is the cornerstone of any streetwear wardrobe. Made from 100% combed ring-spun cotton for an ultra-soft feel. Features the iconic STR=T logo on the chest, a relaxed fit, and reinforced shoulder seams for longevity.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#1a1a1a", "#ffffff", "#374151", "#7f1d1d"],
    colorNames: ["Black", "White", "Gray", "Crimson"],
    inStock: true,
    featured: true,
    trending: false,
  },
  {
    id: 4,
    name: "Cargo Jogger Pants",
    category: "Pants",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 289,
    badge: "HOT",
    image: "https://picsum.photos/seed/cargojogger/800/1000",
    images: [
      "https://picsum.photos/seed/cargojogger/800/1000",
      "https://picsum.photos/seed/cargojogger2/800/1000",
      "https://picsum.photos/seed/cargojogger3/800/1000",
      "https://picsum.photos/seed/cargojogger4/800/1000",
    ],
    description:
      "The Cargo Jogger Pants redefine functional streetwear. Featuring 6 utility pockets, an elastic waistband with adjustable drawstring, tapered leg silhouette, and a comfortable cotton-blend fabric. The perfect blend of style and practicality.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#1a1a1a", "#374151", "#4b5320", "#292524"],
    colorNames: ["Black", "Slate", "Olive", "Earth"],
    inStock: true,
    featured: true,
    trending: true,
  },
  {
    id: 5,
    name: "Oversized Bomber Jacket",
    category: "Jackets",
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.9,
    reviews: 156,
    badge: "NEW",
    image: "https://picsum.photos/seed/bomberjacket/800/1000",
    images: [
      "https://picsum.photos/seed/bomberjacket/800/1000",
      "https://picsum.photos/seed/bomberjacket2/800/1000",
      "https://picsum.photos/seed/bomberjacket3/800/1000",
      "https://picsum.photos/seed/bomberjacket4/800/1000",
    ],
    description:
      "The Oversized Bomber Jacket makes a bold statement. Featuring premium nylon shell with satin lining, ribbed collar, cuffs and hem, front zip closure, and multiple interior pockets. An instant wardrobe upgrade.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#1a1a1a", "#1e3a5f", "#374151", "#7f1d1d"],
    colorNames: ["Black", "Navy", "Gray", "Burgundy"],
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: 6,
    name: "Chain Logo Cap",
    category: "Accessories",
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.5,
    reviews: 521,
    badge: "HOT",
    image: "https://picsum.photos/seed/chaincap/800/1000",
    images: [
      "https://picsum.photos/seed/chaincap/800/1000",
      "https://picsum.photos/seed/chaincap2/800/1000",
      "https://picsum.photos/seed/chaincap3/800/1000",
      "https://picsum.photos/seed/chaincap4/800/1000",
    ],
    description:
      "The Chain Logo Cap adds the perfect finishing touch to any fit. Features an embroidered chain-link logo on the front, structured 6-panel design, adjustable snapback closure, and premium cotton construction.",
    sizes: ["One Size"],
    colors: ["#1a1a1a", "#ffffff", "#4b5320"],
    colorNames: ["Black", "White", "Olive"],
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: 7,
    name: "Tech Fleece Zip-Up",
    category: "Hoodies",
    price: 99.99,
    originalPrice: 129.99,
    rating: 4.7,
    reviews: 198,
    badge: "SALE",
    image: "https://picsum.photos/seed/techfleece/800/1000",
    images: [
      "https://picsum.photos/seed/techfleece/800/1000",
      "https://picsum.photos/seed/techfleece2/800/1000",
      "https://picsum.photos/seed/techfleece3/800/1000",
      "https://picsum.photos/seed/techfleece4/800/1000",
    ],
    description:
      "The Tech Fleece Zip-Up combines athletic performance with street style. Made from innovative tech fleece fabric that provides warmth without bulk. Features full-length zipper, paneled construction, and slim fit profile.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#1a1a1a", "#1e3a5f", "#4c1d95"],
    colorNames: ["Black", "Navy", "Purple"],
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: 8,
    name: "Graphic Print Tee",
    category: "T-Shirts",
    price: 49.99,
    originalPrice: 64.99,
    rating: 4.6,
    reviews: 334,
    badge: "NEW",
    image: "https://picsum.photos/seed/graphictee/800/1000",
    images: [
      "https://picsum.photos/seed/graphictee/800/1000",
      "https://picsum.photos/seed/graphictee2/800/1000",
      "https://picsum.photos/seed/graphictee3/800/1000",
      "https://picsum.photos/seed/graphictee4/800/1000",
    ],
    description:
      "The Graphic Print Tee is a wearable canvas of street culture. Features an oversized fit, premium screen-printed graphic, and high-quality cotton blend fabric that holds its shape wash after wash.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#1a1a1a", "#ffffff", "#374151"],
    colorNames: ["Black", "White", "Ash Gray"],
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: 9,
    name: "Tactical Cargo Shorts",
    category: "Pants",
    price: 59.99,
    originalPrice: 74.99,
    rating: 4.5,
    reviews: 267,
    badge: null,
    image: "https://picsum.photos/seed/tacticalshorts/800/1000",
    images: [
      "https://picsum.photos/seed/tacticalshorts/800/1000",
      "https://picsum.photos/seed/tacticalshorts2/800/1000",
      "https://picsum.photos/seed/tacticalshorts3/800/1000",
      "https://picsum.photos/seed/tacticalshorts4/800/1000",
    ],
    description:
      "The Tactical Cargo Shorts are built for the urban explorer. 8 functional pockets, ripstop fabric construction, adjustable waistband, and a relaxed fit. Handles everything from skate sessions to casual hangouts.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#1a1a1a", "#4b5320", "#374151"],
    colorNames: ["Black", "Olive", "Slate"],
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: 10,
    name: "High-Top Vulcan",
    category: "Shoes",
    price: 109.99,
    originalPrice: 139.99,
    rating: 4.8,
    reviews: 445,
    badge: "HOT",
    image: "https://picsum.photos/seed/hightopvulcan/800/1000",
    images: [
      "https://picsum.photos/seed/hightopvulcan/800/1000",
      "https://picsum.photos/seed/hightopvulcan2/800/1000",
      "https://picsum.photos/seed/hightopvulcan3/800/1000",
      "https://picsum.photos/seed/hightopvulcan4/800/1000",
    ],
    description:
      "The High-Top Vulcan is a timeless silhouette reimagined for the modern street. Canvas upper with vulcanized rubber sole, cushioned insole, and reinforced toe cap. Built to last, styled to stand out.",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: ["#1a1a1a", "#ffffff", "#7f1d1d"],
    colorNames: ["Black", "White", "Red"],
    inStock: true,
    featured: false,
    trending: true,
  },
  {
    id: 11,
    name: "Crossbody Street Bag",
    category: "Accessories",
    price: 64.99,
    originalPrice: 84.99,
    rating: 4.7,
    reviews: 189,
    badge: "NEW",
    image: "https://picsum.photos/seed/crossbodybag/800/1000",
    images: [
      "https://picsum.photos/seed/crossbodybag/800/1000",
      "https://picsum.photos/seed/crossbodybag2/800/1000",
      "https://picsum.photos/seed/crossbodybag3/800/1000",
      "https://picsum.photos/seed/crossbodybag4/800/1000",
    ],
    description:
      "The Crossbody Street Bag is the ultimate carry-all for the urban lifestyle. Features water-resistant nylon construction, adjustable strap, multiple zip compartments, and a sleek minimal design.",
    sizes: ["One Size"],
    colors: ["#1a1a1a", "#374151", "#4b5320"],
    colorNames: ["Black", "Gray", "Olive"],
    inStock: true,
    featured: false,
    trending: false,
  },
  {
    id: 12,
    name: "Coach Street Jacket",
    category: "Jackets",
    price: 134.99,
    originalPrice: 169.99,
    rating: 4.8,
    reviews: 223,
    badge: "SALE",
    image: "https://picsum.photos/seed/coachstreet/800/1000",
    images: [
      "https://picsum.photos/seed/coachstreet/800/1000",
      "https://picsum.photos/seed/coachstreet2/800/1000",
      "https://picsum.photos/seed/coachstreet3/800/1000",
      "https://picsum.photos/seed/coachstreet4/800/1000",
    ],
    description:
      "The Coach Street Jacket brings vintage vibes to modern streets. Wind-resistant woven fabric, press-stud closure, two front pockets, and a relaxed silhouette. A classic that never goes out of style.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["#1a1a1a", "#1e3a5f", "#4b5320"],
    colorNames: ["Black", "Navy", "Olive"],
    inStock: true,
    featured: false,
    trending: true,
  },
]

export const categories = [
  {
    id: 1,
    name: "Hoodies",
    image: "https://picsum.photos/seed/cathoodies/600/700",
    count: 24,
    slug: "hoodies",
  },
  {
    id: 2,
    name: "T-Shirts",
    image: "https://picsum.photos/seed/cattshirts/600/700",
    count: 36,
    slug: "t-shirts",
  },
  {
    id: 3,
    name: "Pants",
    image: "https://picsum.photos/seed/catpants/600/700",
    count: 18,
    slug: "pants",
  },
  {
    id: 4,
    name: "Accessories",
    image: "https://picsum.photos/seed/cataccessories/600/700",
    count: 42,
    slug: "accessories",
  },
  {
    id: 5,
    name: "Shoes",
    image: "https://picsum.photos/seed/catshoes/600/700",
    count: 29,
    slug: "shoes",
  },
  {
    id: 6,
    name: "Jackets",
    image: "https://picsum.photos/seed/catjackets/600/700",
    count: 15,
    slug: "jackets",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Marcus Johnson",
    role: "Streetwear Enthusiast",
    avatar: "https://picsum.photos/seed/marcus/100/100",
    rating: 5,
    text: "STREET has completely transformed my wardrobe. The quality is unmatched — every piece feels premium, the stitching is perfect, and the fits are exactly what the lookbook shows. The Urban Runner Pro is now my daily driver. Can't recommend enough.",
  },
  {
    id: 2,
    name: "Aisha Chen",
    role: "Fashion Blogger",
    avatar: "https://picsum.photos/seed/aisha/100/100",
    rating: 5,
    text: "I've been following STREET since day one and they consistently deliver. The Street Core Hoodie is insanely soft and the colorways are fire. My followers always ask where I get my fits. Fast shipping too — arrived in 2 days!",
  },
  {
    id: 3,
    name: "Tyler Brooks",
    role: "Skateboarder",
    avatar: "https://picsum.photos/seed/tyler/100/100",
    rating: 5,
    text: "Finally a brand that gets it. The Cargo Jogger Pants hold up to serious use — I've been skating in them for months and they look as good as day one. The pocket placement is actually functional. This is my go-to brand now.",
  },
  {
    id: 4,
    name: "Sofia Reyes",
    role: "Creative Director",
    avatar: "https://picsum.photos/seed/sofia/100/100",
    rating: 5,
    text: "The attention to detail at STREET is what separates them from the rest. From the packaging to the garment tags to the actual clothing — everything is considered. The Oversized Bomber Jacket is a masterpiece. Zero complaints.",
  },
]

export const heroSlides = [
  {
    id: 1,
    title: "DEFINE YOUR",
    titleAccent: "STREET STYLE",
    subtitle: "Premium streetwear crafted for those who move with intention. Quality that speaks, style that lasts.",
    cta: "Shop Now",
    ctaLink: "/products",
    image: "https://picsum.photos/seed/hero1/600/800",
    badge: "NEW COLLECTION",
  },
  {
    id: 2,
    title: "NEW SEASON",
    titleAccent: "NEW DROPS",
    subtitle: "Fresh silhouettes, premium materials, and bold colorways to elevate your everyday look.",
    cta: "Explore Collection",
    ctaLink: "/products",
    image: "https://picsum.photos/seed/hero2/600/800",
    badge: "SS 2025",
  },
  {
    id: 3,
    title: "BUILT FOR",
    titleAccent: "THE STREETS",
    subtitle: "Engineered for urban life. Every stitch, every fabric, every detail designed with purpose.",
    cta: "Shop Now",
    ctaLink: "/products",
    image: "https://picsum.photos/seed/hero3/600/800",
    badge: "LIMITED EDITION",
  },
]

export const getFeaturedProducts = () => products.filter((p) => p.featured)
export const getTrendingProducts = () => products.filter((p) => p.trending)
export const getProductById = (id) => products.find((p) => p.id === parseInt(id))
export const getRelatedProducts = (id, category) =>
  products.filter((p) => p.category === category && p.id !== parseInt(id)).slice(0, 4)
